### PR TITLE
Properly close open file handlers with PYVIPS image backend

### LINKED ISSUE #237: SlideImage doesn't close file handlers with PYVIPS backend
**Describe the bug**
When we use the `SlideImage.from_file_path()` to open a whole slide image with PYVIPS as backend, the file handlers aren't closed.

**To Reproduce**
Use the following function which lists the open file handlers created by a given process.

```
import dlup
from dlup import SlideImage
from pathlib import Path
import psutil
import os

def get_open_file_handlers() -> list[Path]:
    process_id = os.getpid()
    process = psutil.Process(process_id)
    open_files = process.open_files()
    
    open_file_handlers = []
    for open_file in open_files:
        file_name = Path(open_file.path)
        if file_name.suffix == ".svs":
            open_file_handlers.append(file_name)
    return open_file_handlers

slide_image_path = Path("path-to-your-wsi.svs")
with SlideImage.from_file_path(slide_image_path, backend="PYVIPS", internal_handler="pil") as slide_image:
    print(slide_image.mpp)

print(get_open_file_handlers())
```
But as can be seen below, there is a file handler that isn't closed. When this function is used in downstream applications, it could lead to too many open files error. See [here](https://github.com/NKI-AI/ahcore/issues/96).

image

However, when we change the backend to OPENSLIDE, there is proper behavior.

image

**Expected behavior**
When we run the example above with PYVIPS backend, the `get_open_file_handlers()` should return an empty list because the context manager is expected to close all open file handlers.

**Environment**
dlup version: 0.5.1
How installed: pip
Python version: 3.11
Operating System: Linux

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by AjeyPaiK**
Fixes #237

### CODE REVIEW

**Comment by BPdeRooij** [comment]
The PR looks good to me. Properly closing the `self._image` in the PyVipsSlide backend fixes the issue. The PyVipsSlide does not have proper tests in `tests/test_backend.py`. If we want PyVipsSlide as the main backend for dlup, the tests should be similar to the tests on OpenSlideSlide and TifffileSlide. I do recall that there were some issues with testing of the PyVipsSlide backend before. It would be interesting to discuss here and to hear your input.

**Comment by jonasteuwen** [comment]
There is a 73% coverage for the pyvips backend through other tests. There was a difficulty testing because the tests were still written for OpenSlide. Now this has been improved. To get 100% test coverage we would need to monkey-patch some parts. The major important parts are tested.

**Review by jonasteuwen — COMMENTED** [review]
LGTM, but I have modified code as well.

**Comment by AjeyPaiK** [comment]
Thanks for the review Bart

**Pull request merged**
