### PR TITLE
added new parameter and according changes so that limit bounds or oth…

### LINKED ISSUE #160: Annotations made by HALO for mrxs slide are not read correctly due to limit bounds
**Describe the bug**
When loading an mrxs slide with limit_bounds true and an annotation with the TiledROIDataset.from_standard_tiling. It will not produce the correct annotations, but annotations at an offset equal to the limit bounds as HALO annotations are apperently not taking limit bounds into account in their coordinates.

**To Reproduce**
A clear and concise description on how to reproduce the problem.
Load slide image and halo annotation using the WsiAnnotations.from_halo_xml and make a dataset using TiledROIsSlideImageDataset.from_standard_tiling with limit_bounds=True. Visualize to check.

**Expected behavior**
Expect the annotations to be returned in the good coordinate system in which the images are as well.

**Environment**
dlup version: 0.3.25
How installed: pip install -e .
Python version: 3.10
Operating System:

**Additional context**

### PR DESCRIPTION
**Pull request by moerlemans**
Offsets can be taken into account when usign the dataset with annotations on mrxs files

Fixes #160

### CODE REVIEW

**Comment by jonasteuwen** [comment]
Can you rebase? Also, the CI/CD should pass

**Comment by jonasteuwen** [comment]
Make sure CI passes. Run it before you commit, that will also save some CI time.

**Comment by jonasteuwen** [comment]
I suggest a different way to implement this. 

In the WsiAnnotations, you can make a parameter `_requires_offset_to_slide_bounds`, which you set to True if you read HaloXML. In the `read_region` you subsequently check if this variable is "True", and if so use the limit_bounds variable.

**Comment by jonasteuwen** [comment]
@moerlemans can you rebase once #201 is merged?

**Comment by moerlemans** [comment]
The problem is that the limit bounds variable is given by the slide. Which the WsiAnnotation has no access to. So this should be an argument to read region or to the init of wsi annotations. I feel like this last option would be best, initialize it to be zero and use it in read_region. The issue has only appeared for me when using halo xml, but I think it will happen with other types as well probably

**Comment by jonasteuwen** [comment]
@moerlemans Can you properly rebase because now you've modified 34 files?

I think you can do something like this:

Add `_offset_with_slide_bounds = False` to the `WsiAnnotations` class. Add a property with `@property` named `offset_with_slide_bounds` that returns this (so it can only be set within the class itself). Now, you can add this to the constructor of `WsiAnnotations`, and set it by default to False, and in the Halo constructor, you add this.

Now in the dataset class you an instance check if it is `WsiAnnotations` or just `_offset = getattr(annotations, "offset_with_slide_bounds", (0, 0))` and add this to the region.

**Comment by jonasteuwen** [comment]
I think #204 fixes this

**Comment by moerlemans** [comment]
Indeed this is fixed in #204

**Pull request closed without merging**
